### ISSUE TITLE
Write generic records with variable schema

### ISSUE THREAD

**Issue by brantian** [googleapis/nodejs-bigquery-storage#331]
Hello!

Is it possible to use this client to create a single method for writing to different tables?

I currently have a implementation for that using the legacy write API, with a function that writes data for different BigQuery tables like doing the following:

```
    const bigquery = require('@google-cloud/bigquery');
    await bigquery
      .dataset(datasetId)
      .table(tableId)
      .insert(data); // data is an array of JSON objects
```

I want to migrate that to the Storage Write API, as this is recommended in the docs for new projects, but I can't figure out how to work with this kind of write operation using protobuf. We work with a high number of different tables and schemas, which change a lot with time, so that's why we want to have a single method for inserting into different tables

Thanks!

**Comment by shollyman** [comment]
Apologies on the lack of feedback here.  The key difference between the legacy streaming API (aka bigquery tabledata.insertall) and the write API is that the user needs to provide a reference schema.  There's also examples (via the managedwriter wrapper) that demonstrate json-based writing, and converting the table's schema automatically into a reference descriptor.  Given that, a single method is certainly possible but depending on your specific needs it's unclear how much state you may wish to maintain about a destination.

I'm going to close this issue due to its age and relative open-endedness, but if you have a more specific question please open a followup issue with the details.
