### ISSUE TITLE
Date type value in typescript as input to TIMESTAMP filed results in '1970-01-01 00:00:00 UTC'

### ISSUE THREAD

**Issue by huilingwei** [googleapis/nodejs-bigquery-storage#419]
Hi,
I am using [nodejs-bigquery-storage](https://github.com/googleapis/nodejs-bigquery-storage)  API: Append_rows_json_writer_default to insert data to Big Query. For timestamp field, when input new Date(), the data store in BigQuery will be '1970-01-01 00:00:00 UTC'. It will be OK when using value Date.now()*1000. 

Is there any problem to input new Date() for the timestamp field?

Thanks,
Huiling

**Comment by huilingwei** [comment]
Hi,

Can anyone help to check what is the problem?

Thanks,
Huiling

**Comment by alvarowolfx** [comment]
hey @huilingwei, thanks for the report. This is due to the way the `protobuf.js` library encodes dates, datetimes and timestamps. 

[The BigQuery Storage Write API docs mentions how each data type needs to be send](https://cloud.google.com/bigquery/docs/write-api#data_type_conversions). This [sample](https://github.com/googleapis/nodejs-bigquery-storage/blob/8ee9e75c2f3de4dee66f710e117c3577c0bef993/samples/append_rows_table_to_proto2.js) have examples for most of the date types. 
* Datetime: `The value must be a  BigQuery DATETIME or TIME literal.` We recommend using the bigquery.datetime method to create a such literal string: https://github.com/googleapis/nodejs-bigquery-storage/blob/8ee9e75c2f3de4dee66f710e117c3577c0bef993/samples/append_rows_table_to_proto2.js#L141
* Date: `The value is the number of days since the Unix epoch (1970-01-01).` https://github.com/googleapis/nodejs-bigquery-storage/blob/8ee9e75c2f3de4dee66f710e117c3577c0bef993/samples/append_rows_table_to_proto2.js#L134
* Timestamp: `The value is given in microseconds since the Unix epoch (1970-01-01).` Example: https://github.com/googleapis/nodejs-bigquery-storage/blob/8ee9e75c2f3de4dee66f710e117c3577c0bef993/samples/append_rows_table_to_proto2.js#L170

That sample is going to be improved by PR #420, but I'll explore more on how to do that conversion automatically.

**Comment by galah92** [comment]
Hi @alvarowolfx, thank you for your answer.
Will #420 allow me to use Date freely for a TIMESTAMP field? If not, will you consider adding it? I think it makes sense ergonomically.

**Comment by huilingwei** [comment]
Hi @alvarowolfx, thank you for your answer. Number for micro seconds will got the correct value, that is OK. 

About Date, wrong time stored to Big Query seems confused.  It's better to work- correct data is stored into Big Query; otherwise I would expect an error response to tell invalid type, similar like this: 
The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)

**Comment by alvarowolfx** [comment]
> Hi @alvarowolfx, thank you for your answer. Will #420 allow me to use Date freely for a TIMESTAMP field? If not, will you consider adding it? I think it makes sense ergonomically.

No, #420 is not gonna allow that. I did more investigation and opened PR #422 with such improvements, but I still need more time to test it and make it more seamless to users.

**Comment by alvarowolfx** [comment]
> Hi @alvarowolfx, thank you for your answer. Number for micro seconds will got the correct value, that is OK.
> 
> About Date, wrong time stored to Big Query seems confused. It's better to work- correct data is stored into Big Query; otherwise I would expect an error response to tell invalid type, similar like this: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)

The error `The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)` comes from Protobufjs trying to encode the Javascript `Date` type, which is not supported by the package. What I'm doing on PR #422 is to inspect the objects passed to the JSONWriter and convert the Javascript `Date` to the representation that BigQuery expects.

**Comment by galah92** [comment]
> > Hi @alvarowolfx, thank you for your answer. Will #420 allow me to use Date freely for a TIMESTAMP field? If not, will you consider adding it? I think it makes sense ergonomically.
> 
> No, #420 is not gonna allow that. I did more investigation and opened PR #422 with such improvements, but I still need more time to test it and make it more seamless to users.

Great! Let me know if there's anyway I can help.

**Comment by huilingwei** [comment]
> > Hi @alvarowolfx, thank you for your answer. Number for micro seconds will got the correct value, that is OK.
> > About Date, wrong time stored to Big Query seems confused. It's better to work- correct data is stored into Big Query; otherwise I would expect an error response to tell invalid type, similar like this: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)
> 
> The error `The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)` comes from Protobufjs trying to encode the Javascript `Date` type, which is not supported by the package. What I'm doing on PR #422 is to inspect the objects passed to the JSONWriter and convert the Javascript `Date` to the representation that BigQuery expects.

Hi @alvarowolfx, thanks a lot.
