### ISSUE TITLE
Using adapt convertStorageSchemaToProto2Descriptor Converts TIMESTAMP and NUMERIC fields to string

### ISSUE THREAD

**Issue by Ashenn1** [googleapis/nodejs-bigquery-storage#424]
It seems proto2 descriptor encodes these two types as string, and they fail with type errors like
`TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (12.4)`
We are trying to migrate from insertAll method but we faced this issue.
For now we edited the schema and changed `TIMESTAMP` type to `STRING` and `NUMERIC` to `FLOAT` as a workaround.

#### Environment details

  - OS: Mac
  - Node.js version: 20
  - npm version: 9.6.7
  - `@google-cloud/bigquery-storage` version: 4.2.1

#### Steps to reproduce

Trying to write this example event to a BQ table returns errors,

Schema Example: 

```
    "fields": [
      {
        "name": "total_val",
        "type": "NUMERIC",
        "mode": "REQUIRED"
      },
      {
        "name": "test_timestamp",
        "type": "TIMESTAMP",
        "mode": "REQUIRED"
      }
    ]
```

```ts

  const storageSchema = adapt.convertBigQuerySchemaToStorageTableSchema(schema);
  const protoDescriptor = adapt.convertStorageSchemaToProto2Descriptor(
      storageSchema,
      'root'
  );
  const connection = await writerClient.createStreamConnection({
      destinationTable: `projects/foo-project-id/datasets/test_dataset/tables/test-table`
  });
  const writer = new JSONWriter({
      connection: connection,
      protoDescriptor: protoDescriptor,
  });
  const event = {
      test_timestamp: '2024-02-15T09:22:33Z',
      total_val: 12.4
  };
  const result: IAppendRowsResponse = await writer.appendRows([event]).getResult();

```

Error for the timestamp field : `Error: interior hyphen
    at Function.fromString`
For the numeric field : `TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (12.4)`

**Comment by germanamz** [comment]
Look like theres no type coercion for `NUMERIC` values and the goto is `STRING`.

By changing `NUMERIC` to `FLOAT` this gets fixed.

**Comment by eduhenke** [comment]
it seems that the issue is still present for the timestamp field

**Comment by alvarowolfx** [comment]
> it seems that the issue is still present for the timestamp field

sorry @eduhenke , ended up missing the comment because this issue was closed. Are you trying to send as a TIMESTAMP in string format ? on PR #436 it was added support for the Javascript DATE class, so it will be automatically converted to the expected representation on the BigQuery Storage API. The challenge is that the proto descriptor is not always generated based on the table schema using the `adapt` package from this SDK, so we can't be 100% sure what was the original column type to be able to convert automatically. For example, if we have a `string` input and the output is an `int64` ( expected data type in protobuf for `timestamp` columns), we don't know if the user have a column of type `INT64` or `TIMESTAMP`. 

Can you open a separated issue on that and show more of your use case ? I'll investigate here what we can do to keep some information about the destination table. Maybe the `StreamConnection` need to fetch the table schema anyway to make those conversions more accurate.

**Comment by fetimo** [comment]
For what it's worth I also encountered this when using a TIMESTAMP format and got the error "Error: internal hyphen".

For me, the fix was to handle TIMESTAMPs like so:

```javascript
if (obj[fieldName] && fieldType === "TIMESTAMP") {
    result[fieldName] = Math.floor(new Date(obj[fieldName]).getTime() / 1000);
}
```

The internal hyphen message comes from long which is a dependency of @grpc/proto-loader which is required by @grpc/grpc-js which is required by google-gax which is required by @google-cloud/bigquery-storage!
